import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import blogs from "./post/generate_info.json";

import styles from "../styles/Home.module.css";

interface BlogInfo {
  id: number;
  title: string;
  number: number;
  labels: { id: number; name: string }[];
}

const Home: NextPage<{ blogs: BlogInfo[] }> = ({ blogs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>recardinal&apos; blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {blogs.map(({ title, id }) => (
          <li key={id}>
            <Link href={`/post/${title}`}>{title}</Link>
          </li>
        ))}
      </ul>
    </div>
  );
};

export function getStaticProps() {
  return {
    props: { blogs },
  };
}

export default Home;
